// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var str = "string";

var arr = /* array */[
  1,
  3,
  4
];

console.log(str);

var $$char = /* "s" */115;

var num = 1.2;

var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.$$char = $$char;
exports.str = str;
exports.num = num;
exports.list = list;
exports.arr = arr;
/*  Not a pure module */
